# Generated by Django 5.2 on 2026-09-28 (squashed from store 0001-0065)

import apps.store.models
import django.db.models.deletion
import meta.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('ordering', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Группы',
                'ordering': ('ordering',),
            },
        ),
        migrations.CreateModel(
            name='VariableItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('dimention', models.CharField(blank=True, max_length=255, null=True)),
                ('is_primary', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, default='static/images/blank_prodimg.jpg', max_length=255, null=True, upload_to='uploads/brands/')),
                ('thumbnail', models.ImageField(blank=True, max_length=255, null=True, upload_to='uploads/brands/')),
                ('ordering', models.PositiveSmallIntegerField(default=0)),
                ('country', models.CharField(blank=True, max_length=255, null=True)),
                ('is_on', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'verbose_name': 'Производитель',
                'verbose_name_plural': 'Производители',
                'indexes': [models.Index(fields=['is_on', 'ordering'], name='store_brand_is_on_e6a38b_idx')],
            },
            bases=(apps.store.models.ImageProcessingMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('ordering', models.PositiveSmallIntegerField(default=0)),
                ('is_features', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, default='static/images/blank_prodimg.jpg', max_length=255, null=True, upload_to='uploads/categories/')),
                ('main_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.maincategory')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ('ordering',),
            },
            bases=(apps.store.models.ImageProcessingMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('sku', models.PositiveSmallIntegerField(unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена с НДС')),
                ('price_wo_tax', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена без НДС')),
                ('is_features', models.BooleanField(default=False)),
                ('is_sale', models.BooleanField(default=False)),
                ('is_bestseller', models.BooleanField(default=False)),
                ('is_visible', models.BooleanField(default=True)),
                ('is_in_sales_price', models.BooleanField(db_index=True, default=False)),
                ('article', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(blank=True, default='static/images/blank_prodimg.jpg', max_length=255, null=True, upload_to='uploads/products/')),
                ('partlist', models.ImageField(blank=True, max_length=255, null=True, upload_to='uploads/products/partlists/')),
                ('thumbnail', models.ImageField(blank=True, max_length=255, null=True, upload_to='uploads/products/thumb/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('keywords', models.CharField(blank=True, max_length=255, null=True)),
                ('ordering', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('in_stock', models.PositiveSmallIntegerField(blank=True, default=1, null=True)),
                ('has_patent', models.BooleanField(default=False)),
                ('is_import', models.BooleanField(db_index=True, default=False, verbose_name='Импортный товар')),
                ('analog', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analog_of', to='store.product')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='store.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='store.category')),
                ('parts', models.ManyToManyField(blank=True, related_name='used_in', to='store.product')),
                ('similar_products', models.ManyToManyField(blank=True, to='store.product')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ('-created_at', 'title'),
            },
            bases=(apps.store.models.ImageProcessingMixin, meta.models.ModelMeta, models.Model),
        ),
        migrations.CreateModel(
            name='Patent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_number', models.CharField(max_length=255, verbose_name='Номер документа')),
                ('publication_date', models.DateField(verbose_name='Дата публикации')),
                ('image', models.ImageField(blank=True, max_length=255, null=True, upload_to='uploads/patents/', verbose_name='Схема')),
                ('document_image', models.ImageField(blank=True, max_length=255, null=True, upload_to='uploads/patents/', verbose_name='Бланк патента')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('library', models.CharField(blank=True, max_length=255, null=True, verbose_name='Библиотека')),
                ('link', models.URLField(blank=True, null=True, verbose_name='Ссылка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patent', to='store.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Патент',
                'verbose_name_plural': 'Патенты',
            },
            bases=(apps.store.models.ImageProcessingMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ProductFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500, verbose_name='Вопрос')),
                ('answer', models.TextField(verbose_name='Ответ')),
                ('ordering', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='store.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQ',
                'ordering': ('ordering',),
            },
        ),
        migrations.CreateModel(
            name='Variable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product')),
                ('varitem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.variableitem')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='variables',
            field=models.ManyToManyField(related_name='variables', through='store.Variable', to='store.variableitem'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['main_category', 'slug'], name='store_categ_main_ca_93dbdd_idx'),
        ),
        migrations.AddIndex(
            model_name='variable',
            index=models.Index(fields=['product', 'varitem'], name='store_varia_product_d1a45f_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category', 'is_visible'], name='store_produ_categor_5d1f08_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['brand', 'is_visible'], name='store_produ_brand_i_ed3bb9_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_features', 'is_visible'], name='store_produ_is_feat_164d17_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_bestseller', 'is_visible'], name='store_produ_is_best_b5541a_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['sku'], name='store_produ_sku_8a55cb_idx'),
        ),
    ]
