# Generated by Django 5.2 on 2026-10-01 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_one_piece_price',
            field=models.BooleanField(default=False),
        ),
    ]
