# Generated by Django 5.2 on 2026-10-01 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_category_is_one_piece_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Имя')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('phone', models.CharField(blank=True, default='', max_length=40, verbose_name='Телефон')),
                ('comment', models.TextField(blank=True, default='', verbose_name='Комментарий')),
                ('source_url', models.URLField(blank=True, default='', max_length=500, verbose_name='Страница')),
                ('is_handled', models.BooleanField(default=False, verbose_name='Обработан')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_requests', to='store.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Запрос цены',
                'verbose_name_plural': 'Запросы цены',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['is_handled', '-created_at'], name='store_price_is_hand_fcc3bd_idx')],
            },
        ),
    ]
