# Generated by Django 4.0.6 on 2022-07-08 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_product_options_product_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_features',
            field=models.BooleanField(default=False),
        ),
    ]
