# Generated by Django 4.0.6 on 2022-07-13 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_product_options_alter_category_ordering'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sku',
            field=models.PositiveSmallIntegerField(default=1010140),
            preserve_default=False,
        ),
    ]
