# Generated by Django 4.0.6 on 2022-07-15 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_remove_product_thumbnail_product_thumbnail_200_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='thumbnail_200',
            new_name='thumbnail',
        ),
        migrations.RemoveField(
            model_name='product',
            name='thumbnail_60',
        ),
    ]
