# Generated by Django 4.0.6 on 2022-07-19 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_alter_product_image_alter_product_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='brand',
        ),
    ]
