# Generated by Django 4.0.6 on 2022-07-21 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_product_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='image',
            field=models.ImageField(blank=True, default='static/images/blank_prodimg.jpg', null=True, upload_to='uploads/brands/'),
        ),
        migrations.AddField(
            model_name='brand',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/brands/'),
        ),
    ]
