# Generated by Django 4.0.6 on 2022-07-25 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_variableitem_variable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variable',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product'),
        ),
        migrations.AlterField(
            model_name='variable',
            name='varitem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='store.variableitem'),
        ),
    ]
