# Generated by Django 4.0.6 on 2022-07-25 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_alter_variable_product_alter_variable_varitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='variables',
            field=models.ManyToManyField(related_name='products', through='store.Variable', to='store.variableitem'),
        ),
    ]
