# Generated by Django 4.0.6 on 2022-07-27 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0024_product_variables'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='variables',
            field=models.ManyToManyField(related_name='variables', through='store.Variable', to='store.variableitem'),
        ),
        migrations.AlterField(
            model_name='variable',
            name='value',
            field=models.CharField(max_length=255),
        ),
    ]
