# Generated by Django 4.0.6 on 2022-07-27 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0025_alter_product_variables_alter_variable_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variableitem',
            name='dimention',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
