# Generated by Django 4.0.6 on 2024-10-22 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0029_maincategory_category_main_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_features',
            field=models.BooleanField(default=False),
        ),
    ]
