# Generated by Django 5.1.2 on 2025-05-21 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0034_product_is_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='analog',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analog_of', to='store.product'),
        ),
        migrations.AddField(
            model_name='product',
            name='parts',
            field=models.ManyToManyField(blank=True, related_name='used_in', to='store.product'),
        ),
        migrations.AddField(
            model_name='product',
            name='similar_products',
            field=models.ManyToManyField(blank=True, to='store.product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='store.category'),
        ),
    ]
