# Generated by Django 5.2 on 2025-05-26 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0035_product_analog_product_parts_and_more'),
    ]

    # operations = [
    # ]

    operations = [
        # migrations.RunSQL(
        #     sql="CREATE EXTENSION IF NOT EXISTS pg_trgm;",
        #     reverse_sql="DROP EXTENSION IF EXISTS pg_trgm;"
        # ),
        # migrations.RunSQL(
        #     sql="""
        #         CREATE INDEX product_title_trgm_idx
        #           ON product
        #           USING gin (title gin_trgm_ops);
        #         CREATE INDEX product_description_trgm_idx
        #           ON product
        #           USING gin (description gin_trgm_ops);
        #     """,
        #     reverse_sql="""
        #         DROP INDEX IF EXISTS product_title_trgm_idx;
        #         DROP INDEX IF EXISTS product_description_trgm_idx;
        #     """
        # ),
    ]
