# Generated by Django 5.2 on 2025-05-26 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0036_auto_20250526_1047'),
    ]

    # operations = [
    # ]

    operations = [
        migrations.RunSQL(
            sql="CREATE EXTENSION IF NOT EXISTS pg_trgm;",
            reverse_sql="DROP EXTENSION IF EXISTS pg_trgm;"
        ),
    ]
