# Generated by Django 5.2 on 2025-06-10 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0037_auto_20250528_1047'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, default='static/images/blank_prodimg.jpg', null=True, upload_to='uploads/brands/'),
        ),
    ]
