# Generated by Django 5.2 on 2025-07-09 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0038_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='partlist',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/products/partlists/'),
        ),
    ]
