# Generated by Django 5.2 on 2025-08-11 10:04

import django_summernote.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0039_product_partlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='summer_description',
            field=django_summernote.fields.SummernoteTextField(default=''),
        ),
    ]
