# Generated by Django 5.2 on 2025-08-11 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0040_category_summer_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='summer_description',
        ),
    ]
