# Generated by Django 5.2 on 2025-08-11 10:11

import django_summernote.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0041_remove_category_summer_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='summer_description',
            field=django_summernote.fields.SummernoteTextField(default=''),
        ),
    ]
