# Generated by Django 5.2 on 2025-10-04 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0043_product_keywords'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='summer_description',
        ),
    ]
