# Generated by Django 5.2 on 2025-10-03 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0043_product_keywords'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_in_sales_price',
            field=models.BooleanField(default=False),
        ),
    ]
