# Generated by Django 5.2 on 2025-10-04 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0044_remove_category_summer_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price_wo_tax',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
