# Generated by Django 5.2 on 2025-10-04 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0044_product_is_in_sales_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price_wo_tax',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
