# Generated by Django 5.2 on 2025-10-05 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0045_product_price_wo_tax'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Цена с НДС'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_wo_tax',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Цена без НДС'),
        ),
    ]
