# Generated by Django 5.2 on 2025-10-07 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0046_alter_product_price_alter_product_price_wo_tax'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ordering',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
