# Generated by Django 5.2 on 2025-10-27 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0047_product_ordering'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='brand',
        #     name='country',
        #     field=models.CharField(blank=True, max_length=255, null=True),
        # ),
        # migrations.AddField(
        #     model_name='brand',
        #     name='ordering',
        #     field=models.PositiveSmallIntegerField(default=0),
        # ),
    ]
