# Generated by Django 5.2 on 2025-10-27 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0048_brand_country_brand_ordering'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='is_on',
            field=models.BooleanField(default=True),
        ),
    ]
