# Generated by Django 5.2 on 2025-11-25 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0049_brand_is_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='variableitem',
            name='is_primary',
            field=models.BooleanField(default=False),
        ),
    ]
