# Generated by Django 4.0.6 on 2025-10-30 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0049_brand_is_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='summer_description',
        ),
    ]
