# Generated by Django 5.2 on 2026-01-04 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0049_brand_country_brand_is_on_brand_ordering'),
    ]

    operations = [
        migrations.AddField(
            model_name='variableitem',
            name='is_primary',
            field=models.BooleanField(default=False),
        ),
    ]
