# Generated by Django 4.0.6 on 2025-11-26 11:59

from django.db import migrations, models
import django_summernote.fields


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0050_remove_category_summer_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='variableitem',
            name='is_primary',
            field=models.BooleanField(default=False),
        ),
    ]
