# Generated by Django 5.2 on 2026-02-18 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0050_variableitem_is_primary'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='in_stock',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
