# Generated by Django 5.2 on 2026-02-18 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0051_product_in_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='in_stock',
            field=models.CharField(blank=True, default='Много', max_length=255, null=True),
        ),
    ]
