# Generated by Django 5.2 on 2026-02-18 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0052_alter_product_in_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='in_stock',
            field=models.PositiveSmallIntegerField(blank=True, default=1, null=True),
        ),
    ]
