# Generated by Django 5.2 on 2026-05-12 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0053_alter_product_in_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_number', models.CharField(max_length=255, verbose_name='Номер документа')),
                ('publication_date', models.DateField(verbose_name='Дата публикации')),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/patents/', verbose_name='Схема')),
                ('document_image', models.ImageField(blank=True, null=True, upload_to='uploads/patents/', verbose_name='Бланк патента')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('library', models.CharField(blank=True, max_length=255, null=True, verbose_name='Библиотека')),
                ('link', models.URLField(blank=True, null=True, verbose_name='Ссылка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('product', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patent', to='store.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Патент',
                'verbose_name_plural': 'Патенты',
            },
        ),
    ]
