# Generated by Django 4.0.6 on 2026-05-07 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0051_category_summer_description_variableitem_is_primary'),
        ('store', '0053_alter_product_in_stock'),
    ]

    operations = [
    ]
