# Generated by Django 5.2.14 on 2026-06-04 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0054_patent'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='has_patent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='patent',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='store.product', verbose_name='Товар'),
        ),
    ]
