# Generated by Django 5.2 on 2026-05-12 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0054_patent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patent',
            name='library',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Библиотека'),
        ),
    ]
