# Generated by Django 5.2 on 2026-05-12 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0055_alter_patent_library'),
    ]

    operations = [
        migrations.AddField(
            model_name='patent',
            name='document_image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/patents/', verbose_name='Бланк патента'),
        ),
        migrations.AlterField(
            model_name='patent',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/patents/', verbose_name='Схема'),
        ),
    ]
