# Generated by Django 5.2.14 on 2026-06-29 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0056_add_productfaq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, default='static/images/blank_prodimg.jpg', null=True, upload_to='uploads/categories/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена с НДС'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_wo_tax',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена без НДС'),
        ),
    ]
