# Generated by Django 5.2.14 on 2026-06-29 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0057_decimal_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='main_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.maincategory'),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='store.brand'),
        ),
        migrations.AlterField(
            model_name='variable',
            name='varitem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.variableitem'),
        ),
    ]
