# Generated by Django 5.2.14 on 2026-05-14 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0057_alter_patent_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Patent',
        ),
    ]
