# Generated by Django 5.2 on 2026-07-02 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0057_alter_patent_product'),
        ('store', '0059_add_indexes'),
    ]

    operations = [
    ]
