# Generated by Django 5.2 on 2026-07-07 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0060_merge_0057_alter_patent_product_0059_add_indexes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='summer_description',
        ),
    ]
