# Generated by Django 5.2 on 2026-07-12 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0061_remove_category_summer_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_import',
            field=models.BooleanField(default=False, verbose_name='Импортный товар'),
        ),
    ]
