# Generated by Django 5.2 on 2026-07-17 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0062_add_is_import'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='is_on',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_import',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Импортный товар'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_in_sales_price',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddIndex(
            model_name='brand',
            index=models.Index(fields=['is_on', 'ordering'], name='store_brand_is_on_e6a38b_idx'),
        ),
        migrations.AddIndex(
            model_name='variable',
            index=models.Index(fields=['product', 'varitem'], name='store_varia_product_d1a45f_idx'),
        ),
    ]
