# Generated by Django 5.2 on 2026-07-17 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0063_alter_brand_is_on_alter_product_is_import_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='image',
            field=models.ImageField(blank=True, default='static/images/blank_prodimg.jpg', max_length=255, null=True, upload_to='uploads/brands/'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='thumbnail',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='uploads/brands/'),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, default='static/images/blank_prodimg.jpg', max_length=255, null=True, upload_to='uploads/categories/'),
        ),
        migrations.AlterField(
            model_name='patent',
            name='document_image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='uploads/patents/', verbose_name='Бланк патента'),
        ),
        migrations.AlterField(
            model_name='patent',
            name='image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='uploads/patents/', verbose_name='Схема'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='static/images/blank_prodimg.jpg', max_length=255, null=True, upload_to='uploads/products/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='partlist',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='uploads/products/partlists/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='thumbnail',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='uploads/products/thumb/'),
        ),
    ]
