# Generated by Django 4.0.6 on 2024-01-31 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_category_name_alter_post_title'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='PostCategory',
        ),
        migrations.AlterModelOptions(
            name='postcategory',
            options={'verbose_name_plural': 'postcategories'},
        ),
    ]
