# Generated by Django 4.0.6 on 2024-10-17 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_rename_category_postcategory_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='category',
            new_name='postcategory',
        ),
    ]
