# Generated by Django 5.2 on 2025-06-17 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_rename_category_post_postcategory'),
        ('store', '0038_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='linked_products',
            field=models.ManyToManyField(blank=True, related_name='linked_products', to='store.product'),
        ),
    ]
