# Generated by Django 5.2 on 2025-10-04 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_post_linked_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='linked_products',
        ),
    ]
