# Generated by Django 5.2.14 on 2026-06-04 11:35
# NOTE: This migration is intentionally empty. The RemoveField was moved to 0009.

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_remove_post_categories'),
    ]

    operations = []
