# Generated by Django 5.2 on 2026-05-12 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_remove_post_linked_products'),
        ('store', '0053_alter_product_in_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='linked_products',
            field=models.ManyToManyField(blank=True, related_name='linked_products', to='store.product'),
        ),
    ]
