# Generated by Django 5.2 on 2026-05-12 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_post_linked_products'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='post',
        #     name='categories',
        # ),
    ]
