# Generated by Django 5.2 on 2026-05-12 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_remove_post_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='postcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.postcategory'),
        ),
        migrations.AlterField(
            model_name='postcategory',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
