"""
Django settings for katran project.

Generated by 'django-admin startproject' using Django 4.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

from pathlib import Path
import os
# from django.utils.encoding import force_str
# Build paths inside the project like this: BASE_DIR / 'subdir'.

BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-(2q3sp-o%k!2t5x6#qg^@)(+t@-xoc@@8#^@g*sne@ih8s900w'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Cart
SESSION_COOKIE_AGE = 86400
CART_SESSION_ID = 'cart'
SITE_ID = 1
# Application definition
INSTALLED_APPS = [

    
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.sitemaps',
    'django.contrib.staticfiles',
    
    'apps.cart',
    'apps.core',
    'apps.store',
    'apps.order',
    'apps.blog',

    'phonenumber_field',
    'fontawesomefree',
    'django_summernote',
    'django.contrib.sites',
    'meta',
    'html5lib',
    
    # 'django_json_ld',

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    "django.middleware.security.SecurityMiddleware",
    "apps.core.middleware.WwwRedirectMiddleware",
    'csp.middleware.CSPMiddleware',
    # "django.middleware.csp.ContentSecurityPolicyMiddleware",
]

ROOT_URLCONF = 'katran.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                
                # store
                'apps.store.context_processors.menu_category',
                'apps.store.context_processors.featured_product',
                'apps.store.context_processors.all_products',
                'apps.store.context_processors.menu_brands',
                'apps.store.context_processors.featured_categories',
                'apps.store.context_processors.featured_product_success',
                'apps.store.context_processors.bestsellers_product',
                
                # cart
                'apps.cart.context_processors.cart',

                # blog
                'apps.blog.context_processors.all_posts',                

                
            ],
        },
    },
]
SUMMERNOTE_CONFIG = {
    'iframe': True,
    # "jquery": "summernoteJQuery",

    'summernote': {

        'width': '1024px'
    }
}

SUMMERNOTE_THEME = 'lite'

WSGI_APPLICATION = 'katran.wsgi.application'

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'WARNING',
        },
        'core.views': {  # замените на имя вашего приложения
            'handlers': ['console'],
            'level': 'WARNING',
            'propagate': False,
        },
    },
}


# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

#LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True
USE_L10N = False

LANGUAGE_CODE = 'ru-RU'

# Пример вывода: 16 сентября 2012 
DATE_FORMAT = 'd E Y'


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

STATIC_URL = '/static/'

STATICFILES_DIRS = [
    Path(__file__).parent.joinpath(BASE_DIR, 'static')
]


MEDIA_URL = '/media/'
MEDIA_ROOT = Path(__file__).parent.joinpath(BASE_DIR, 'media/')

# STATIC_URL = '/static/'
# STATICFILES_DIRS = [
#     os.path.join(BASE_DIR, 'static')
# ]
# MEDIA_URL = '/media/'
# MEDIA_ROOT = os.path.join(BASE_DIR, 'media/')

# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
handler404 = 'apps.core.views.error_404_view'
handler500 = 'apps.core.views.error_500_view'

APPEND_SLASH = True

SECURE_SSL_REDIRECT = True

SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Указывает Django использовать заголовок HTTP Strict Transport Security (HSTS)

SECURE_HSTS_SECONDS = 31536000  # Год

SECURE_HSTS_INCLUDE_SUBDOMAINS = True

SECURE_HSTS_PRELOAD = True

# Указывает браузерам отправлять куки только через защищенное HTTPS-соединение

SESSION_COOKIE_SECURE = True

CSRF_COOKIE_SECURE = True

# Отправляет полный URL для запросов в пределах одного происхождения, только происхождение — для кросс-доменных запросов. Баланс между безопасностью и аналитикой. 

SECURE_REFERRER_POLICY = 'strict-origin-when-cross-origin'

# Указывает Django использовать безопасные куки

SECURE_BROWSER_XSS_FILTER = True

SECURE_CONTENT_TYPE_NOSNIFF = True


# Email settings
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.spaceweb.ru' # или ваш SMTP-сервер
EMAIL_PORT = 25
EMAIL_USE_TLS = False
EMAIL_HOST_USER = 'office@katran-pnevmo.ru' # Ваш email
EMAIL_HOST_PASSWORD = 'x3n@War10R' # Пароль от вашего email
DEFAULT_FROM_EMAIL = 'office@katran-pnevmo.ru' # Email, от которого будут отправляться письма

# WWW Redirect
PREPEND_WWW = False

JSON_LD_DEFAULT_TYPE = 'Product'

META_SITE_PROTOCOL = 'https'
META_SITE_DOMAIN = '127.0.0.1:8000'
META_USE_SCHEMAORG_PROPERTIES = True