# Generated by Django 5.2 on 2026-07-07 17:36

import django.db.models.deletion
import django_summernote.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0061_remove_category_summer_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название отрасли')),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('icon_class', models.CharField(blank=True, default='', help_text='Например: fa-solid fa-ship', max_length=64, verbose_name='CSS-класс иконки (FontAwesome)')),
                ('short_description', models.TextField(blank=True, default='', verbose_name='Краткое описание (для карточки)')),
                ('description', django_summernote.fields.SummernoteTextField(blank=True, default='', verbose_name='Полное описание (HTML)')),
                ('recommended_tools', models.TextField(blank=True, default='', help_text='Текст или HTML со списком рекомендуемых категорий', verbose_name='Рекомендуемый инструмент')),
                ('meta_title', models.CharField(blank=True, default='', max_length=255, verbose_name='Meta Title')),
                ('meta_description', models.CharField(blank=True, default='', max_length=500, verbose_name='Meta Description')),
                ('meta_keywords', models.CharField(blank=True, default='', max_length=500, verbose_name='Meta Keywords')),
                ('ordering', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Видимость')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('related_categories', models.ManyToManyField(blank=True, to='store.category', verbose_name='Связанные категории каталога')),
            ],
            options={
                'verbose_name': 'Отрасль',
                'verbose_name_plural': 'Отрасли',
                'ordering': ('ordering', 'title'),
            },
        ),
        migrations.CreateModel(
            name='CaseStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название кейса')),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('client_name', models.CharField(blank=True, default='', max_length=255, verbose_name='Название клиента (если можно показать)')),
                ('problem', models.TextField(verbose_name='Задача / Проблема')),
                ('solution', models.TextField(verbose_name='Наше решение')),
                ('result', models.TextField(blank=True, default='', verbose_name='Результат')),
                ('body', django_summernote.fields.SummernoteTextField(blank=True, default='', verbose_name='Подробное описание (HTML)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/case_studies/', verbose_name='Главное фото')),
                ('metric_label', models.CharField(blank=True, default='', max_length=128, verbose_name='Метрика (напр. «Рост производительности»)')),
                ('metric_value', models.CharField(blank=True, default='', max_length=64, verbose_name='Значение метрики (напр. «27%»)')),
                ('meta_title', models.CharField(blank=True, default='', max_length=255, verbose_name='Meta Title')),
                ('meta_description', models.CharField(blank=True, default='', max_length=500, verbose_name='Meta Description')),
                ('ordering', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Видимость')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('related_products', models.ManyToManyField(blank=True, to='store.product', verbose_name='Задействованные продукты')),
                ('industry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='solutions.industry', verbose_name='Отрасль')),
            ],
            options={
                'verbose_name': 'Кейс',
                'verbose_name_plural': 'Кейсы',
                'ordering': ('ordering', '-created_at'),
            },
        ),
    ]
