# Generated by Django 5.2 on 2026-07-17 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solutions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casestudy',
            name='image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='uploads/case_studies/', verbose_name='Главное фото'),
        ),
    ]
