# Generated by Django 5.2 on 2026-05-13 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0056_patent_document_image_alter_patent_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patent',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patent', to='store.product', verbose_name='Товар'),
        ),
    ]
