# Generated by Django 5.2 on 2026-09-23 09:27

import django.db.models.deletion
import django_summernote.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0064_alter_brand_image_alter_brand_thumbnail_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlossaryPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_type', models.CharField(choices=[('term', 'Wiki-термин / глоссарий'), ('scenario', 'Сценарий / задача'), ('guide', 'Как выбрать'), ('category', 'SEO-текст категории')], default='term', max_length=20, verbose_name='Тип страницы')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Slug')),
                ('short_description', models.TextField(blank=True, default='', verbose_name='Краткое описание (для карточки в списке)')),
                ('body', django_summernote.fields.SummernoteTextField(blank=True, default='', verbose_name='Основной контент (HTML)')),
                ('faq', models.JSONField(blank=True, default=list, verbose_name='FAQ (JSON: [{"q": "...", "a": "..."}])')),
                ('meta_title', models.CharField(blank=True, default='', max_length=255, verbose_name='Meta Title')),
                ('meta_description', models.CharField(blank=True, default='', max_length=500, verbose_name='Meta Description')),
                ('meta_keywords', models.CharField(blank=True, default='', max_length=500, verbose_name='Meta Keywords')),
                ('ordering', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Видимость')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.category', verbose_name='Связанная категория (для SEO-текста категории)')),
                ('related_categories', models.ManyToManyField(blank=True, related_name='glossary_pages', to='store.category', verbose_name='Связанные категории каталога')),
                ('related_products', models.ManyToManyField(blank=True, to='store.product', verbose_name='Связанные товары')),
            ],
            options={
                'verbose_name': 'Страница справочника',
                'verbose_name_plural': 'Страницы справочника',
                'ordering': ('page_type', 'ordering', 'title'),
                'indexes': [models.Index(fields=['page_type', 'is_visible'], name='glossary_gl_page_ty_bf89a8_idx'), models.Index(fields=['slug'], name='glossary_gl_slug_3c334b_idx')],
            },
        ),
    ]
