# Generated by Django 5.2 on 2026-09-23 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glossary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='glossarypage',
            name='page_type',
            field=models.CharField(choices=[('term', 'Wiki-термин / глоссарий'), ('scenario', 'Сценарий / задача'), ('guide', 'Как выбрать'), ('category', 'SEO-текст категории'), ('model', 'Конкретная модель / бестселлер')], default='term', max_length=20, verbose_name='Тип страницы'),
        ),
    ]
