# Generated by Django 5.2 on 2026-09-23 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glossary', '0002_alter_glossarypage_page_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='glossarypage',
            name='related_pages',
            field=models.ManyToManyField(blank=True, to='glossary.glossarypage', verbose_name='Связанные страницы справочника'),
        ),
    ]
