# Generated by Django 5.2 on 2026-09-23 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glossary', '0003_glossarypage_related_pages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='glossarypage',
            name='body',
            field=models.TextField(blank=True, default='', verbose_name='Основной контент (HTML)'),
        ),
    ]
